[server]
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
magicEnabled = true
fastReruns = true

[client]
showErrorDetails = true
toolbarMode = "auto"

[logger]
level = "info"
messageFormat = "%(asctime)s - %(message)s"

[deprecation]
showfileUploaderEncoding = false
showPyplotGlobalUse = false

[global]
developmentMode = false 